/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pt.isel

import kotlin.test.Test
import kotlin.test.assertEquals

class LoggerTest {
    @Test fun `log fields of Point`() {
        val out = PrinterBuffer();
        val logger = Logger(out, MemberKind.FIELD)
        val p = Point(5, 7)
        logger.log(p)
        assertEquals("Point: x = 5, y = 7, ", out.buffer())
    }
    @Test fun `log properties of Point`() {
        val out = PrinterBuffer();
        val logger = Logger(out, MemberKind.PROPERTY)
        val p = Point(5, 7)
        logger.log(p)
        assertEquals("Point: Module = 8.602325267042627, X = 5, Y = 7, ", out.buffer())
    }
}
