/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pt.isel

import kotlin.test.Test
import kotlin.test.assertEquals

class LoggerTest {

    @Test fun `log properties of Student`() {
        val out = PrinterBuffer();
        val logger = LoggerDynamic.logger(
            MemberKind.PROPERTY,
            out,
            Student::class.java)
        val s = Student(131324, "Ze Manel")
        logger.log(s)
        assertEquals("Student: name = Ze Manel, nr = 131324, ", out.buffer())
    }

}
